<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>VendingIdle.SimTest</RootNamespace>
    <AssemblyName>VendingIdle.SimTest</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\VendingIdle.Core\VendingIdle.Core.csproj" />
  </ItemGroup>

</Project>
