<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>VendingIdle</RootNamespace>
    <AssemblyName>VendingIdle</AssemblyName>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VendingIdle.Core\VendingIdle.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>

</Project>
